//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evaluant.Uss.SqlMapper.Mapping
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "sqlm";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Evaluant.Uss";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Evaluant";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID SqlMapperMappingDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(SqlMapperMappingCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID SqlMapperMappingExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(SqlMapperMappingCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewSqlMapperMappingExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(SqlMapperMappingCommandSetId), 0x0001);
	
		// Package identifier
		public const string SqlMapperMappingPackageId = "dc2ca4a9-94ff-457f-ab1b-44975f1e1e1d";
		
		// Editor factory identifier
		public const string SqlMapperMappingEditorFactoryId = "656a4d1c-4e0d-4a6c-b278-1335cef46f5e";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string SqlMapperMappingModelExplorerToolWindowId = "40bd32a7-3ce9-4e55-9dc8-23a2add2cefc";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Evaluant.Uss.SqlMapper.Mapping
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string SqlMapperMappingCommandSetId = "a795c6d7-6414-4fff-a7fd-16791b38f7fa";
	}
}